runtime:
  device: "cuda"                                      # Options: "cpu", "cuda"
  compute_type: "float16"                             # Options: "int8", "float16"
  cuda_alloc_conf: "expandable_segments:True"         # PyTorch CUDA Memory Management

language:
  audio: "ko"                                         # Options: "en", "ko", "tr"
  text: "ko"                                          # Options: "en", "ko", "tr"

models:
  openai:
    model_name: "gpt-4o"                              # Options: "gpt-4", "gpt-4o", etc.
    openai_api_key: "${OPENAI_API_KEY}"

  azure_openai:
    model_name: "gpt-4o"                              # Options: "gpt-4", "gpt-4o", etc.
    azure_openai_api_key: "${AZURE_OPENAI_API_KEY}"
    azure_openai_api_base: "${AZURE_OPENAI_API_BASE}"
    azure_openai_api_version: "${AZURE_OPENAI_API_VERSION}"

  mpsenet:
    model_name: "JacobLinCool/MP-SENet-DNS"           # Options: "JacobLinCool/MP-SENet-DNS", "JacobLinCool/MP-SENet-VB"
